- name: get makemkvcon stat
  stat:
    path: /usr/bin/makemkvcon
  register: makemkvcon_st
- import_tasks: makemkv-bin.yml
  when: not makemkvcon_st.stat.exists
- name: get makemkv stat
  stat:
    path: /usr/bin/makemkv
  register: makemkv_st
- import_tasks: makemkv-oss.yml
  when: not makemkv_st.stat.exists
