- name: install groovy
  shell: "source {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install groovy"
  args:
    creates: "{{ ansible_env.HOME }}/.sdkman/candidates/groovy"
- name: install scala
  shell: "source {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install scala"
  args:
    creates: "{{ ansible_env.HOME }}/.sdkman/candidates/scala"
