- name: list rvm keys
  shell: gpg2 --list-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  register: list_keys_result
  ignore_errors: yes
- name: install rvm gpg keys
  shell: gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  when: list_keys_result.rc != 0
- name: install ruby build dependencies
  dnf:
    name: autoconf,automake,bison,libffi-devel,libtool,libyaml-devel,readline-devel,sqlite-devel
    state: present
  become: yes
- name: install rvm and ruby
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby
  args:
    creates: "{{ ansible_env.HOME }}/.rvm/rubies/default"
- name: get gem path
  shell: source /home/whs/.rvm/scripts/rvm && echo $(ruby -r rubygems -e 'puts Gem.user_dir')/bin
  register: gem_path_result
  args:
    executable: /bin/bash
- name: get rake stat
  stat:
    path: "{{ gem_path_result.stdout }}/rake"
  register: rake_st
- name: install rake
  shell: source /home/whs/.rvm/scripts/rvm && gem install rake --user-install
  when: not rake_st.stat.exists
  args:
    executable: /bin/bash
